name: Deploy to Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make deploy script executable
        run: chmod +x .github/workflows/scripts/deploy.sh

      - name: Trigger Amplify
        env:
          AMPLIFY_WEBHOOK: ${{ secrets.AMPLIFY_WEBHOOK }}
        run: ./.github/workflows/scripts/deploy.sh
