name: Deploy to Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - uses: actions/checkout@v4

      - name: Trigger Amplify
        run: |
          curl -X POST -d '{}' "${{ secrets.AMPLIFY_WEBHOOK }}"
